### ISSUE TITLE
We have an issue

### ISSUE THREAD

**Issue by catarinabrg** [2DegreesInvesting/onboarding-demo#1]
#This is a test
**Help** us @maurolepore 
[Our google docs](https://docs.google.com/document/d/1y4hYVA7N7vu5VQhWA8wioanRmJ7SL5St_QiErCqTp-k/edit#)
@MonikaFu _also needs help_

**Comment by MonikaFu** [comment]
help is coming @catarinabrg

**Comment by maurolepore** [comment]
Thanks @catarinabrg and @MonikaFu for joining me today. I've updated the readme to reflect what we did today. I'll keep this repo for 1 week, then delete it to keep the 2DII org clean.

I really look forward to supporting your work. Pleas do reach out to me with your questions and suggestions.

I'll close this issue now.
